name: Template Call
 
on:
  push:
    branches: [main]

permissions:
  security-events: write
  actions: read
  contents: read


jobs:
  scan-dojo:
    uses: gastonbarbaccia/global_actions/.github/workflows/dojo_v2.yml@main
#    with:
#      DEFECTDOJO_PRODUCT_NAME: "global_actions_demo"
#      DEFECTDOJO_PRODUCTID: "1"
